# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-24 13:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formstest', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='blogposts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.SlugField()),
                ('post', models.TextField(max_length=512)),
            ],
        ),
        migrations.DeleteModel(
            name='blogpost',
        ),
    ]
