# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-24 13:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formstest', '0002_auto_20160224_1311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogposts',
            name='name',
            field=models.SlugField(unique=True),
        ),
    ]
