# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-24 13:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formstest', '0003_auto_20160224_1347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogposts',
            name='name',
            field=models.SlugField(),
        ),
    ]
